const LoremPage = () => {
    return (<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pharetra lorem quis posuere malesuada. Aenean a gravida nisl. Cras efficitur eget nisi non tincidunt. Mauris lobortis ut dui nec bibendum. Ut ex tellus, vehicula non dolor in, imperdiet volutpat lectus. Fusce dictum maximus neque, in faucibus lectus pellentesque a. Nulla facilisi. Sed ornare rutrum neque scelerisque placerat. Maecenas tempor fringilla semper. Aenean quis purus nec sem vehicula vestibulum at et tellus. Quisque a risus facilisis, dapibus sapien ut, efficitur eros. Integer a ultrices mi. Vivamus nec molestie odio, eget cursus velit. Vestibulum efficitur tellus a mauris hendrerit, non viverra lacus gravida. Proin quis ex eget sapien luctus elementum. Sed pellentesque nec dui ut tincidunt.

        Pellentesque nec maximus ipsum. Praesent ultricies gravida mi eget tempus. Nunc mattis tempus nisl. Maecenas libero tortor, pulvinar eu auctor eu, congue sit amet lacus. In vel leo sit amet sapien rutrum luctus non eget odio. Proin ligula sem, gravida a ipsum et, venenatis elementum nunc. Integer non nulla sed risus fringilla consequat vel nec nunc. Nulla facilisi. Integer convallis lectus at rhoncus efficitur.
        
        Integer vel ligula felis. Pellentesque in accumsan sem. Sed lorem dolor, porttitor ac diam nec, posuere congue tortor. Nullam massa justo, tincidunt ut elit in, viverra accumsan urna. Etiam scelerisque odio quis lorem cursus, ut placerat massa ullamcorper. Ut iaculis dictum lorem id fringilla. Cras ipsum ante, lobortis sit amet justo a, fermentum ullamcorper ante. Integer elementum pharetra nulla, id volutpat neque elementum porta. Maecenas vulputate sed sem et tincidunt. Mauris nulla lectus, porttitor sed maximus et, bibendum a leo. Cras eget viverra nibh. Fusce non velit vel mauris pulvinar laoreet quis eget massa. Praesent sed risus ex. Ut tincidunt ante nec odio fermentum, non consequat ante aliquet.
        
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer massa risus, dictum quis semper vitae, euismod in purus. Praesent at nisi massa. Phasellus nisi augue, auctor quis mattis sit amet, placerat sed urna. In hac habitasse platea dictumst. Phasellus ut erat nibh. Suspendisse et imperdiet lorem, at finibus enim. Aliquam erat volutpat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec porta dui venenatis vehicula eleifend. Nullam auctor commodo leo, et accumsan lacus finibus vel. Donec tincidunt sapien at lorem mattis, sit amet facilisis tellus consectetur. Quisque auctor vel nunc nec feugiat. Donec ultrices arcu enim, et mollis lorem egestas nec.
        
        Donec ac ornare metus, eget aliquam tortor. Integer sagittis mollis egestas. Nam est mi, malesuada eget feugiat vitae, dictum nec magna. Vivamus blandit sodales purus, et sollicitudin ligula tincidunt in. Ut sapien lectus, aliquam sit amet consequat a, ultrices ac purus. Proin vitae molestie magna. Aliquam semper mauris quis auctor condimentum. Nullam in cursus erat, eget mattis neque. Etiam quis ligula lectus. Proin at aliquam neque, id fermentum massa.
        
        In venenatis commodo accumsan. Aliquam id faucibus justo. Vestibulum convallis nibh a ante euismod vestibulum. Suspendisse ut enim sed odio molestie lacinia. Sed leo arcu, volutpat sit amet ante nec, dapibus dapibus lorem. Etiam pharetra lectus ante. Sed id rutrum mi. Fusce tempor dolor eget ipsum volutpat bibendum. Donec eget blandit odio. Curabitur placerat justo arcu, interdum pulvinar dui tincidunt in. Sed volutpat consequat augue. Vestibulum efficitur, nunc eu tincidunt malesuada, nibh mi volutpat sapien, vitae tempor turpis quam quis odio. Integer dictum turpis sit amet finibus lobortis. Vivamus et auctor nisi. Vivamus fermentum arcu at sem fringilla consectetur. Aliquam erat volutpat.
        
        Curabitur a enim et mauris rutrum aliquam non nec enim. Nunc nisi neque, aliquet non neque in, varius aliquam dolor. Integer finibus facilisis ante, ut fringilla lectus tempor rutrum. Etiam ut sollicitudin libero. Fusce pretium aliquet nisl eget maximus. Pellentesque lobortis justo in mauris hendrerit, eget eleifend lacus finibus. Morbi sit amet felis semper, faucibus urna et, sodales neque. Integer nisi nulla, maximus id finibus quis, fermentum at risus. Mauris risus lorem, auctor eget sapien sollicitudin, condimentum dapibus dui. Nullam vel ullamcorper velit. Praesent condimentum libero metus, eu placerat felis egestas ac. Donec id venenatis lectus. Donec auctor metus et purus venenatis vestibulum.
        
        Etiam iaculis tellus lacus, ac eleifend metus auctor a. Suspendisse lacinia porta finibus. Aenean in dolor et eros ullamcorper suscipit ac eget purus. Phasellus sit amet imperdiet tortor, sed elementum ante. Fusce efficitur et nunc et feugiat. Quisque interdum, urna a aliquam iaculis, ex sem pulvinar sapien, in interdum sapien neque vitae mi. Ut commodo ipsum luctus dolor iaculis gravida sed id sapien. Pellentesque vel est ut augue imperdiet gravida. Nunc quis nulla risus. Integer arcu neque, sagittis eget lobortis nec, convallis ut dui. Ut porttitor blandit ultrices. Mauris nibh risus, tristique in viverra eu, blandit vel risus.
        
        Duis elementum risus ut metus varius dignissim. Proin enim felis, efficitur eu neque in, porta auctor enim. Morbi fermentum finibus lorem, quis pellentesque ipsum. Suspendisse potenti. In aliquam, elit sit amet tempus scelerisque, turpis odio vehicula arcu, ac imperdiet risus ante aliquet leo. Donec id tellus pharetra, fringilla urna a, interdum enim. Phasellus ullamcorper scelerisque nisl, nec sollicitudin dolor. Phasellus aliquet magna nisi. Sed mollis arcu eu libero tempus elementum. Donec molestie nunc et tincidunt aliquet. Vestibulum nec nisl ac ligula lobortis facilisis eu in risus. Nulla leo neque, molestie viverra dolor eget, finibus vulputate neque. Etiam pretium risus nisi, eu suscipit dolor laoreet a.
        
        Aenean a accumsan tellus, vel lobortis nisl. Vestibulum nibh metus, hendrerit vitae tempus in, facilisis sed augue. Morbi vulputate quis mauris vitae tristique. Curabitur et leo venenatis, rhoncus diam vitae, dapibus odio. In ut consequat orci, sed finibus nulla. Nulla volutpat, est vel viverra semper, sem sem laoreet arcu, vel blandit purus dui vel felis. Sed dignissim convallis convallis. Donec in hendrerit augue. Integer sagittis nibh sit amet libero efficitur scelerisque. Proin porta auctor metus sed tincidunt.
        
        Donec ut consequat elit. Vestibulum iaculis gravida urna, ac mattis risus ornare vel. Fusce eu dictum enim. Sed varius mauris a rhoncus lobortis. Cras vel commodo nunc, sit amet interdum tellus. Nulla non interdum augue. Cras non orci suscipit risus pretium faucibus in a odio. Suspendisse blandit auctor eleifend. Vestibulum sagittis at leo tincidunt dapibus. Donec condimentum ac ipsum a tempus. Nulla et mauris a metus tempus sagittis.
        
        Maecenas magna nulla, tristique a blandit sit amet, vestibulum eget odio. Nam fermentum purus libero, id iaculis arcu porta eu. Maecenas velit sapien, semper a orci nec, convallis pretium augue. Praesent nunc odio, venenatis ut rutrum eget, fermentum vitae nisl. Mauris tristique mollis congue. Sed non eros et mauris maximus mollis. Duis tristique ante eu elit rutrum, ut condimentum magna sagittis. Mauris elementum varius tortor, in tristique metus blandit vel. Sed id egestas augue, ac tempus tellus.
        
        Maecenas semper pellentesque lorem, in iaculis diam tincidunt ac. Nunc et mi est. Praesent at blandit orci. Nulla in risus purus. Praesent ac interdum erat, non euismod libero. Curabitur dictum ac eros a venenatis. Aenean ultricies ipsum purus, a ullamcorper arcu efficitur vel. Curabitur lacus neque, egestas sit amet iaculis mattis, faucibus non augue. Aliquam efficitur ipsum nec risus malesuada porttitor. Integer id justo at diam ullamcorper fringilla. Suspendisse quis neque libero. Donec eget viverra lacus. Pellentesque dictum semper ligula, vel condimentum neque dignissim sed. Pellentesque augue urna, commodo vitae euismod eget, fringilla non lectus.
        
        Nam sagittis lorem a facilisis vehicula. Vestibulum ultricies, arcu eget scelerisque placerat, libero dui feugiat diam, quis hendrerit diam nunc vel sem. Pellentesque commodo purus vitae felis blandit feugiat. Donec sit amet sollicitudin risus. Mauris eu vehicula odio. Nulla nec volutpat arcu. Pellentesque erat lorem, bibendum vitae dictum eu, vehicula id est. Vivamus sed eros vel ipsum ullamcorper sodales.
        
        Fusce neque mauris, semper in ligula non, tristique dictum urna. Phasellus ut neque ut sapien iaculis ultrices et vel eros. Proin diam elit, elementum et aliquam ut, commodo tincidunt enim. Nunc ipsum urna, faucibus in luctus eu, gravida quis ante. Quisque consectetur leo turpis, eu maximus tellus pretium quis. In eu neque libero. Cras vel est ac magna accumsan vestibulum. Donec cursus semper ultrices. Nunc elementum aliquet ligula sed volutpat. In malesuada, eros id aliquet faucibus, velit arcu maximus nunc, nec elementum nunc libero eget augue. Suspendisse eu tellus nisi. Morbi vulputate leo nec dolor ultrices rutrum.
        
        Duis quis est odio. Nam non sollicitudin felis. Aenean lacinia pharetra suscipit. Pellentesque a massa ac nunc interdum blandit et in lectus. Aliquam ut aliquet urna. Vestibulum efficitur, ipsum at luctus malesuada, justo orci dapibus purus, eget commodo enim dolor suscipit odio. Fusce quis tellus sem. Pellentesque lobortis, eros nec gravida tempor, felis quam ornare mi, ac elementum nisl dolor ut est. Suspendisse sit amet neque metus. Donec vel sapien eu leo volutpat semper at at risus. Etiam sed ex ligula. Suspendisse vel tellus feugiat, hendrerit felis quis, rutrum diam. Praesent convallis diam at erat vulputate ultrices. Nunc ac quam ut mauris pharetra dictum et viverra arcu. Sed quis quam turpis. Aliquam varius rutrum ornare.
        
        Nullam ut dui sollicitudin purus ullamcorper aliquam. Vestibulum viverra erat id augue aliquet ultrices. Praesent sit amet blandit ipsum. Fusce hendrerit pellentesque lacinia. Suspendisse sed augue et lorem faucibus scelerisque et sit amet sem. Maecenas vitae sapien vel ipsum malesuada efficitur. Vestibulum et ultricies leo. Duis ligula eros, viverra semper congue at, lobortis id elit. Sed eget tincidunt dui. Aenean facilisis vehicula lacus non gravida. Vivamus molestie nisi sed massa venenatis, eu efficitur ligula ultrices. Morbi nunc odio, tempor a cursus ut, luctus eget augue. Etiam consequat augue nec tempor gravida. Phasellus ligula nulla, consequat id mi eget, congue lobortis metus. Sed tempus, lectus et pulvinar rutrum, leo nisl dapibus risus, eu tempor ligula augue non lectus.
        
        Nullam congue et purus vestibulum egestas. Nam vitae ex neque. Nulla vestibulum auctor nibh at pellentesque. Cras lectus magna, consequat vitae risus nec, iaculis gravida felis. Donec sed velit at nunc dapibus consectetur id eu nulla. Donec sed ipsum eu augue blandit cursus. Vestibulum condimentum accumsan rhoncus. Fusce a elit ac metus rutrum elementum ut ut leo. Nulla mattis dolor vitae tortor tristique mollis. Praesent vestibulum, magna blandit iaculis efficitur, dolor nisi vehicula diam, non hendrerit tellus elit id neque. Donec eu porttitor quam. Nam luctus dolor aliquet, elementum nunc accumsan, euismod lacus. Curabitur sollicitudin maximus sapien sit amet imperdiet. Phasellus a metus sit amet arcu facilisis faucibus non eget justo. Phasellus ex purus, tristique at quam vitae, varius consectetur arcu. Nam urna ligula, bibendum luctus nisl at, aliquam hendrerit tellus.
        
        Nulla feugiat, lectus quis gravida maximus, urna mauris mollis lectus, et posuere dui elit eu nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin felis risus, pulvinar at dapibus sed, aliquam vitae purus. Cras mattis sapien dictum diam porttitor semper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed et arcu eget augue hendrerit tempor eget at ante. Duis purus odio, rutrum in consequat ac, vehicula sit amet mauris. Nunc interdum commodo eleifend. Vivamus feugiat pretium pharetra. Donec nulla eros, tristique eu commodo in, luctus in neque. Nam vel convallis risus. In consequat lorem sed nisl blandit, nec consectetur ipsum tincidunt. Curabitur ut augue sem. Maecenas a luctus ipsum. Praesent eget risus vel eros tempor auctor a in justo. Suspendisse potenti.
        
        Suspendisse a nibh interdum, eleifend arcu at, ullamcorper dolor. Maecenas finibus elit non justo dapibus rhoncus. Sed vehicula velit aliquam ipsum maximus mattis. Proin aliquam ipsum faucibus nibh sodales, ut mollis massa viverra. Nulla et euismod nisl. Aliquam placerat pretium vulputate. Donec feugiat odio ac volutpat commodo. Vestibulum sagittis nisl est, et accumsan nisl aliquet et. Etiam dignissim porttitor urna cursus sagittis. Nulla facilisi. Duis a eros ac mi rhoncus lobortis ut sit amet ante. Suspendisse fermentum sed dui in ultrices. Duis at orci a nulla facilisis placerat accumsan convallis nibh.</div>);
}
 
export default LoremPage;